// <auto-generated />
using CookingMedia.Authentication.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CookingMedia.Authentication.Entities.Migrations
{
    [DbContext(typeof(AuthenticationDBContext))]
    partial class AuthenticationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CookingMedia.Authentication.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@cm.com",
                            Name = "Admin",
                            Password = "$argon2i$v=19$m=65536,t=3,p=1$ZjVVSktlS1cyYkRRNEdpNA$8gEdYXIzMcxk8CdwrribFoKbVVUrkpg6pDrj52lYSt8",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 1001,
                            Email = "member1@cm.com",
                            Name = "Member1",
                            Password = "$argon2i$v=19$m=65536,t=3,p=1$NTQwOTR5WUs5U0EzTlFWeg$Y2pWpaI9J7g0tXP+YN0ueUvuqkDt0Tv65KCA/U0qE/Q",
                            Role = "Member"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
